name: Milkshake builder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo import
        uses: actions/checkout@v4

      - name: jdk boot
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: bzl boot
        uses: abhinavsingh/setup-bazel@v3

      - name: bzl build
        run: | 
          cd /home/runner/work/milkshake/milkshake && ls && \
          bazel build @milkshake//mod --output_groups=default,executable
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabric-mod.jar
          path: bazel-bin/mod/mod.jar
