name: Milkshake builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5.0.0
      - uses: abhinavsingh/setup-bazel@v3

      - name: Build
      - run: bazel build @milkshake//mod --output_groups=default,executable;

      - name: Upload artifact
      - run: |
          cp bazel-bin/mod/mod.jar ./mod
          git config --global user.name 'pankak'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add mod/mod.jar
          git commit -am 'bye bye :mewing:'
          git push
